# Generated by Django 2.2.7 on 2019-11-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.CharField(help_text='Squirrel ID', max_length=255, primary_key=True, serialize=False)),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Squirel Age', max_length=20)),
                ('color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Squirrel Fur Color', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=15, help_text='Latitude', max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=15, help_text='Longitude', max_digits=19)),
                ('date', models.DateField(help_text='Sighting Date')),
                ('location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=20)),
                ('specifc_location', models.CharField(help_text='Specific Location', max_length=255)),
                ('running', models.BooleanField(default=False, help_text='Running')),
                ('chasing', models.BooleanField(default=False, help_text='Chasing')),
                ('climbing', models.BooleanField(default=False, help_text='Climbing')),
                ('eating', models.BooleanField(default=False, help_text='Eating')),
                ('foraging', models.BooleanField(default=False, help_text='Foraging')),
                ('other_activities', models.CharField(help_text='Other Activities', max_length=255)),
                ('kuks', models.BooleanField(default=False, help_text='Kuks')),
                ('quaas', models.BooleanField(default=False, help_text='Quaas')),
                ('moans', models.BooleanField(default=False, help_text='Moans')),
                ('tail_flags', models.BooleanField(default=False, help_text='Tail flags')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Tail twitches')),
                ('approaches', models.BooleanField(default=False, help_text='Approaches')),
                ('indifferent', models.BooleanField(default=False, help_text='Indifferent')),
                ('runs_from', models.BooleanField(default=False, help_text='Runs from')),
            ],
        ),
        migrations.DeleteModel(
            name='Squirrel',
        ),
    ]
