# Generated by Django 2.2.7 on 2019-11-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191123_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='specifc_location',
            new_name='specific_location',
        ),
    ]
